apiVersion: apps/v1
kind: Deployment
metadata:
  name: sanicapp
spec:
  replicas: 3  # Number of replicas (pods)
  selector:
    matchLabels:
      app: sanicapp
  template:
    metadata:
      labels:
        app: sanicapp
    spec:
      containers:
      - name: sanicapp
        image: pappymm/sanicapp:latest  # Use your pushed image
        ports:
        - containerPort: 8000
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
